### ISSUE TITLE
Uplift this to HTML/CSSOM

### ISSUE THREAD

**Issue by annevk** [arai-a/window-open-features#2]
How do you feel about trying to standardize this? See https://github.com/whatwg/html/issues/2464 for some prior discussion around this functionality.

Also, great work documenting the status quo!

**Comment by arai-a** [comment]
yeah, it would be nice if we can standardize this, and hopefully make the behavior consistent across browsers,
that will help web-devs.
if we standardize, we should look into the behavior of mobile browsers etc as well tho.

about the `IsPopup` condition, Firefox's behavior can be modified.
the current behavior is based on the mix of others and previous behavior about when to open new window,
and, for example, changing it to just using `width` would also work.

**Comment by arai-a** [comment]
Looks like https://html.spec.whatwg.org/multipage/browsers.html#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name is the right place to modify,
given that it's talking about popup blocker.

**Comment by annevk** [comment]
Yeah, though note that what HTML calls a popup is all things that open in a new tab/window, not just windows with a popup look-and-feel.

**Comment by arai-a** [comment]
okay, if there's no distinction between window/tab/popup in https://html.spec.whatwg.org/multipage/browsers.html#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name ,
we can keep using "window open steps" as the modification target,
after https://bugzilla.mozilla.org/show_bug.cgi?id=1661643 gets fixed (that removes "current tab" case).
